version: "3"

services:
  rabbitmq:
    build: 
      context: .
      dockerfile: Dockerfile-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/bitnami"

  redis:
    image: "bitnami/redis:5.0.4"
    env_file:
      - .env.docker-compose.redis
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/bitnami/redis/data"

  celery-flower:
    image: gregsi/latest-celery-flower-docker:latest
    env_file:
      - .env.docker-compose.flower
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
      - redis

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "8080:8080"                               
    env_file:
      - .env.docker-compose.fastapi
    depends_on:
      - rabbitmq
      - redis

  fastworker:
    build:
      context: .
      dockerfile: Dockerfile-worker
    depends_on:
      - rabbitmq
      - redis
    ports:
      - "8888:8888"
    env_file:
      - .env.docker-compose.fastapi

volumes:
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local
